travis:
  secure:
    BINSTAR_TOKEN: faE2JpcUTeZu8Qj5IJ2PHuvf9GB+COMpb1pi9G7q0Nq8TPN+5Z+Rncz3sObzgKzPV/o/1o1sfxQnjHpuQMcBQvxTepAm1+k6+SmimpEVJM4DkUXHAA1JnDZvfvLiBUkHP1rq/7pjA1mJKa/lT9dXp7PmUh0sMrQ3fuB4XYtfNBHVoPtTN1Z/NpaHxE7AMOXGNqXd6Arn5V8JBVEkDY5rZ1AfJqh990nhDmfD6KZM59FQKASrJ/IqsG8RlVQjxuKHrfMlZqh33Qm7Gm3tEXJqe7WwOTYdTWAvSGJ7M0o3PHPZIcif2DCTtQLLRPQtgSzjkpd86YDWZj5lvgWlWXenCJQ56Pk5vQxCQVBi7FYT76IrxIiwk0bO0c8ElhsRNibhdoffeHAhxr4EvC3UJAYB9pLWk/PkkKx6yARJseCLj35xaEAN2i+at/n83kaV0DJZ1b8wJTFCcgmqfkMySDJN9S2Q9v0yLBp42tKVQkCftAZvAYRMLj6fUzXBcvlrm7RSFGurdvf32+J+xquljuK8WqLftcGmxnzeQlak5xcI/TdpGV76nlyac/9J3P070hk+uxLKYxL7BlNGbAb7RYkBV2mRAUzXiN/Gzj2ePqpeC6T7vS4GUKPGRoL1rkPQyeYEBl7XOHQ4i7/xpuxqGUaziLfkKfoNeSJiJOb87GMkPaM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
