travis:
  secure:
    BINSTAR_TOKEN: X0SKRAA4OZeyeurAkP5tbWAi9nzN6TWwiXO1UhXg6V9yItejE/NQLfInpC4xi3jIveiLRUx1hPqEkrGQ88msQGi/dOMo2J/j/2StXnj1MCe8H1HVpbVFWGOBKn7PuYGjdoivD7sqT7rHxVed1/FyyhtU78xMCjQbKoNHbxfx5Lhtod6GWSTRyIvOegaB1ddgdos715sXN7VhC7+W2U9GugVVf10WUGMIZNwvIcCUNjlNjeKjalo09+uFm8xiEdeG8Tc3PD1FqK4NVNA2s1G2PXzc2iON9REjHLvwxvWljiY3aEgrSZVA6xN3juXXBSG9BP0IiddBrYgWc+4MZxQ5P8evL1tDrZow9X40JlZM+JKICa6alqhdSzwHRu0mNL/MC/evAXNgX92iNc48NjGVvJ3qKX7R3YGFFENW9QfOnasg10AvGzy5FWOS41qoAAPCFzHXrI6NOHMheorGcwG7N8hqo8OMgnzgoyQOBrRSR59Cy4Rj3DxdKaqC8tEryd/4miT3IkAuzPXXZi978UlL/P6tRlm5hSjvcrH9x1JIg6aFamOP0DIWzOPJ35ysUuNz254NPWQne3Fup553hzKwLLq6//Y0cJJ7NtWH6TmYzs1ZS6/x07MMyeQNzxsfpDZtvJMd4Zfgp0qTO2t4Zqp8N+C3FnpKNdHqBPVdUhPDr0k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
